# Generated by Django 5.1.2 on 2026-03-21 23:17

import django.core.validators
import reels.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reels", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="videopost",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="videopost",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="videopost",
            name="video",
            field=models.FileField(
                upload_to="videos/",
                validators=[
                    reels.models.validate_video_size,
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "mov", "avi", "webm"]
                    ),
                ],
            ),
        ),
    ]
