# Generated by Django 6.0.4 on 2026-04-22 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0004_remove_post_user_postvideo_postvideocomment_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="postvideolike",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="postvideo",
            name="likes_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="postvideolike",
            name="guest_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="postvideolike",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="liked_videos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="postvideolike",
            index=models.Index(
                fields=["guest_id"], name="videos_post_guest_i_3ad8de_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="postvideolike",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("user", "post"),
                name="unique_user_like",
            ),
        ),
        migrations.AddConstraint(
            model_name="postvideolike",
            constraint=models.UniqueConstraint(
                condition=models.Q(("guest_id__isnull", False)),
                fields=("guest_id", "post"),
                name="unique_guest_like",
            ),
        ),
    ]
