# Generated by Django 6.0.4 on 2026-04-24 21:38

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0005_alter_postvideolike_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postvideo",
            name="file",
        ),
        migrations.AddField(
            model_name="postvideo",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
        migrations.AddField(
            model_name="postvideo",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="videos/"),
        ),
    ]
