# Generated by Django 6.0.4 on 2026-08-05 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0007_recruit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="recruit",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recruit",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recruit",
            name="industry",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="recruit",
            name="prefecture",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="recruit",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "募集中"),
                    ("full", "満員"),
                    ("closed", "終了"),
                    ("cancel", "中止"),
                ],
                default="open",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="recruit",
            name="target_gender",
            field=models.CharField(
                choices=[
                    ("all", "誰でも"),
                    ("male", "男性のみ"),
                    ("female", "女性のみ"),
                ],
                default="all",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="recruit",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="recruit",
            name="category",
            field=models.CharField(
                choices=[
                    ("drink", "飲み"),
                    ("food", "ご飯"),
                    ("karaoke", "カラオケ"),
                    ("cafe", "カフェ"),
                    ("sports", "スポーツ"),
                    ("game", "ゲーム"),
                    ("drive", "ドライブ"),
                    ("study", "勉強"),
                    ("other", "その他"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="RecruitParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "承認待ち"),
                            ("approved", "参加確定"),
                            ("rejected", "拒否"),
                            ("cancelled", "キャンセル"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("message", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recruit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="videos.recruit",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="joined_recruits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("recruit", "user"), name="unique_recruit_participant"
                    )
                ],
            },
        ),
    ]
