# Generated by Django 6.0.4 on 2026-08-09 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0009_alter_recruitparticipant_options_recruitchatroom_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recruit",
            name="cancel_keep_participants",
            field=models.BooleanField(default=False),
        ),
    ]
