# Generated by Django 6.0.4 on 2026-08-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0011_recruitchatread"),
    ]

    operations = [
        migrations.AddField(
            model_name="recruit",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="recruits/"),
        ),
    ]
