# Generated by Django 6.0.4 on 2026-08-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0012_recruit_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="recruit",
            name="latitude",
            field=models.FloatField(blank=True, null=True, verbose_name="募集地点緯度"),
        ),
        migrations.AddField(
            model_name="recruit",
            name="longitude",
            field=models.FloatField(blank=True, null=True, verbose_name="募集地点経度"),
        ),
    ]
