# Generated by Django 6.0.4 on 2026-10-04 06:35

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0013_recruit_latitude_recruit_longitude"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostVideoImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="image"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="videos.postvideo",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
