# Generated by Django 5.1.2 on 2024-12-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
