# Generated by Django 5.1.2 on 2024-12-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0005_alter_page_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="is_public",
            field=models.BooleanField(default=True, verbose_name="☑️で公開"),
        ),
    ]
