# Generated by Django 5.1.2 on 2024-12-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0006_alter_page_is_public"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="is_public",
            field=models.BooleanField(default=False, verbose_name="☑️で公開"),
        ),
    ]
