# Generated by Django 5.1.2 on 2024-12-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0007_alter_page_is_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="likes",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
