# Generated by Django 5.1.2 on 2024-12-27 01:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0008_page_likes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="liked_users",
            field=models.ManyToManyField(
                blank=True, related_name="liked_pages", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
