# Generated by Django 5.1.2 on 2024-12-28 14:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0009_page_liked_users"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="liked_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="liked_pages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="いいねしたユーザー",
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="likes",
            field=models.PositiveIntegerField(default=0, verbose_name="いいね数"),
        ),
    ]
