# Generated by Django 5.1.2 on 2026-03-08 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0011_likerecord"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="page",
            options={"ordering": ["-page_date"]},
        ),
    ]
