# Generated by Django 6.0.4 on 2026-05-21 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0013_alter_page_author_alter_page_body_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuestLikeRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guest_id", models.CharField(max_length=100)),
                ("like_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="diary.page"
                    ),
                ),
            ],
            options={
                "unique_together": {("guest_id", "page")},
            },
        ),
    ]
