# Generated by Django 6.0.4 on 2026-10-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0014_guestlikerecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteNotice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="タイトル")),
                ("message", models.TextField(verbose_name="本文")),
                (
                    "published_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="公開日時"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="公開する"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
            ],
            options={
                "verbose_name": "サイトお知らせ",
                "verbose_name_plural": "サイトお知らせ",
                "ordering": ["-published_at"],
            },
        ),
    ]
