# Generated by Django 5.1.2 on 2024-12-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomparticipant",
            name="is_host",
            field=models.BooleanField(default=False),
        ),
    ]
