# Generated by Django 5.1.2 on 2024-12-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="address",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="任意)住所"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "男性"), ("F", "女性"), ("O", "その他")],
                max_length=10,
                null=True,
                verbose_name="任意)性別",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="password",
            field=models.CharField(
                max_length=100, verbose_name="パスワード (ログインの時使います。)"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                max_length=50,
                unique=True,
                verbose_name="ユーザID (ログインの時使います。他のユーザに見える部分です。)",
            ),
        ),
    ]
