# Generated by Django 5.1.2 on 2025-12-26 03:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_customuser_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="activation_token",
            field=models.UUIDField(
                blank=True, default=uuid.uuid4, editable=False, null=True
            ),
        ),
    ]
