# Generated by Django 5.1.2 on 2026-01-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_supporter",
            field=models.BooleanField(default=False),
        ),
    ]
