# Generated by Django 5.1.2 on 2026-02-23 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_userlike"),
    ]

    operations = [
        migrations.AddField(
            model_name="userlike",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
