# Generated by Django 5.1.2 on 2026-03-21 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_alter_customuser_profile_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_age_verified",
            field=models.BooleanField(default=False, verbose_name="年齢確認済み"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="stripe_verification_session_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
