# Generated by Django 5.1.2 on 2026-03-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_alter_customuser_profile_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_verification_pending",
            field=models.BooleanField(default=False),
        ),
    ]
