# Generated by Django 5.1.2 on 2026-03-25 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_customuser_is_verification_pending"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="is_age_verified",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="is_verification_pending",
        ),
        migrations.AddField(
            model_name="customuser",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("unverified", "未確認"),
                    ("pending", "確認中"),
                    ("verified", "確認済み"),
                    ("failed", "失敗"),
                ],
                default="unverified",
                max_length=20,
            ),
        ),
    ]
