# Generated by Django 5.1.2 on 2026-03-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_remove_customuser_is_age_verified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="verification_attempts",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("unverified", "未確認"),
                    ("pending", "確認中"),
                    ("verified", "確認済み"),
                    ("failed", "失敗"),
                ],
                db_index=True,
                default="unverified",
                max_length=20,
            ),
        ),
    ]
