# Generated by Django 5.1.2 on 2026-03-28 00:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_customuser_verification_attempts_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="stripe_verification_session_id",
        ),
        migrations.RemoveField(
            model_name="verificationlog",
            name="session_id",
        ),
        migrations.CreateModel(
            name="KYCSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_image", models.ImageField(upload_to="kyc/id/")),
                ("selfie_image", models.ImageField(upload_to="kyc/selfie/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "確認中"),
                            ("approved", "承認"),
                            ("rejected", "却下"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
