# Generated by Django 5.1.2 on 2026-04-04 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_alter_kycsubmission_user_footprint"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="agreed_terms_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="terms_version",
            field=models.CharField(default="1.0", max_length=10),
        ),
    ]
