# Generated by Django 5.1.2 on 2026-04-05 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0022_tagcategory_alter_tag_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        choices=[(1, "少し"), (2, "普通"), (3, "かなり")], default=2
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.profile",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.tag"
                    ),
                ),
            ],
            options={
                "unique_together": {("profile", "tag")},
            },
        ),
    ]
