# Generated by Django 5.1.2 on 2026-04-08 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0023_profiletag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profiletag",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile_tags",
                to="accounts.profile",
            ),
        ),
    ]
