# Generated by Django 6.0.4 on 2026-04-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0025_alter_userlike_from_user_alter_userlike_to_user"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="footprint",
            index=models.Index(
                fields=["to_user"], name="accounts_fo_to_user_770ffa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="footprint",
            index=models.Index(
                fields=["-created_at"], name="accounts_fo_created_007aba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(fields=["user1"], name="accounts_ma_user1_i_a8f984_idx"),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(fields=["user2"], name="accounts_ma_user2_i_8e4f21_idx"),
        ),
        migrations.AddIndex(
            model_name="userlike",
            index=models.Index(
                fields=["from_user"], name="accounts_us_from_us_f1628b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userlike",
            index=models.Index(
                fields=["to_user"], name="accounts_us_to_user_a876de_idx"
            ),
        ),
    ]
