# Generated by Django 6.0.4 on 2026-04-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0026_footprint_accounts_fo_to_user_770ffa_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="match",
            name="accounts_ma_user1_i_a8f984_idx",
        ),
        migrations.RemoveIndex(
            model_name="match",
            name="accounts_ma_user2_i_8e4f21_idx",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="profile_image",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "男性"), ("F", "女性"), ("O", "その他")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
