# Generated by Django 6.0.4 on 2026-04-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0027_remove_match_accounts_ma_user1_i_a8f984_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="total_likes",
            field=models.IntegerField(default=0),
        ),
    ]
