# Generated by Django 6.0.4 on 2026-04-29 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0028_customuser_total_likes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="total_likes",
            new_name="received_likes_count",
        ),
    ]
