# Generated by Django 6.0.4 on 2026-05-07 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0029_rename_total_likes_customuser_received_likes_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="auto_home_screen",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="home_screen",
            field=models.CharField(
                choices=[
                    ("feed", "フィード"),
                    ("messages", "メッセージ"),
                    ("index", "ホーム"),
                ],
                default="feed",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="UserPageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_name", models.CharField(max_length=30)),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
