# Generated by Django 6.0.4 on 2026-05-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0030_customuser_auto_home_screen_customuser_home_screen_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="home_screen",
            field=models.CharField(
                choices=[
                    ("feed", "フィード"),
                    ("messages", "メッセージ"),
                    ("index", "ホーム"),
                    ("mypage", "マイページ"),
                    ("frontpage", "掲示板"),
                    ("roomlist", "ビデオチャット"),
                ],
                default="feed",
                max_length=20,
            ),
        ),
    ]
