# Generated by Django 6.0.4 on 2026-05-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0031_alter_customuser_home_screen"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="warning_mail_sent",
            field=models.BooleanField(default=False),
        ),
    ]
