# Generated by Django 6.0.4 on 2026-05-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0032_profile_warning_mail_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="warning_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
