# Generated by Django 6.0.4 on 2026-09-22 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0033_profile_warning_sent_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpiritTitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slot1", models.CharField(blank=True, default="", max_length=30)),
                ("slot2", models.CharField(blank=True, default="", max_length=30)),
                ("slot3", models.CharField(blank=True, default="", max_length=30)),
                ("slot4", models.CharField(blank=True, default="", max_length=30)),
                ("slot5", models.CharField(blank=True, default="", max_length=30)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spirit_title",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
