# Generated by Django 6.0.4 on 2026-09-22 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0034_spirittitle"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpiritTitlePart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slot",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "第1枠"),
                            (2, "第2枠"),
                            (3, "第3枠"),
                            (4, "第4枠"),
                            (5, "第5枠"),
                        ],
                        verbose_name="選択枠",
                    ),
                ),
                ("text", models.CharField(max_length=30, verbose_name="称号パーツ")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="表示順"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["slot", "order", "id"],
                "indexes": [
                    models.Index(
                        fields=["slot", "is_active"], name="accounts_sp_slot_df1f62_idx"
                    )
                ],
            },
        ),
    ]
