# Generated by Django 5.1.2 on 2024-12-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="intro",
        ),
        migrations.AddField(
            model_name="post",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
