# Generated by Django 5.1.2 on 2024-12-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_remove_comment_email_comment_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
