# Generated by Django 5.1.2 on 2024-12-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_comment_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_direct_to_author",
            field=models.BooleanField(default=False),
        ),
    ]
