# Generated by Django 5.1.2 on 2024-12-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_comment_is_direct_to_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="reply_to",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
