# Generated by Django 5.1.2 on 2024-12-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_comment_reply_to"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="is_direct_to_author",
        ),
        migrations.AlterField(
            model_name="comment",
            name="name",
            field=models.CharField(default="No name", max_length=50),
        ),
    ]
