# Generated by Django 5.1.2 on 2024-12-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_remove_comment_is_direct_to_author_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
