# Generated by Django 5.1.2 on 2024-12-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_alter_comment_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
