# Generated by Django 5.1.2 on 2025-12-15 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0012_comment_image_comment_video_post_image_post_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="comment_images/"),
        ),
        migrations.AlterField(
            model_name="post",
            name="posted_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="comment_videos/"),
        ),
    ]
