# Generated by Django 5.1.2 on 2025-12-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0014_post_parent_post_reply_to_alter_post_image_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["posted_date"]},
        ),
        migrations.RemoveField(
            model_name="post",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="post",
            name="reply_to",
        ),
        migrations.AlterField(
            model_name="comment",
            name="name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
