# Generated by Django 5.1.2 on 2025-12-21 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0015_alter_comment_options_remove_post_parent_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="video",
        ),
        migrations.RemoveField(
            model_name="post",
            name="video",
        ),
        migrations.AddField(
            model_name="comment",
            name="youtube_url",
            field=models.URLField(
                blank=True, help_text="YouTubeのURL（限定公開OK）", null=True
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="youtube_url",
            field=models.URLField(
                blank=True, help_text="YouTubeのURL（限定公開OK）", null=True
            ),
        ),
    ]
