# Generated by Django 5.1.2 on 2025-12-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0016_remove_comment_video_remove_post_video_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="youtube_url",
        ),
        migrations.RemoveField(
            model_name="post",
            name="youtube_url",
        ),
        migrations.AddField(
            model_name="comment",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="動画URL（YouTube / TikTok / Instagram / X / Facebook）",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="YouTube / TikTok / Instagram / X / Facebook の動画URL",
                null=True,
            ),
        ),
    ]
