# Generated by Django 5.1.2 on 2025-12-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0017_remove_comment_youtube_url_remove_post_youtube_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="投稿者名"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=255, verbose_name="タイトル"),
        ),
    ]
