# Generated by Django 5.1.2 on 2025-12-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0019_remove_post_name_post_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="表示名"
            ),
        ),
    ]
