# Generated by Django 5.1.2 on 2025-12-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0020_post_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="body",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="post",
            name="video_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
