# Generated by Django 5.1.2 on 2025-12-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0021_alter_post_body_alter_post_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="表示名"
            ),
        ),
    ]
