# Generated by Django 5.1.2 on 2025-12-30 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0022_alter_comment_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
