# Generated by Django 5.1.2 on 2026-01-10 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0023_alter_post_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="live_ended",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="video_type",
            field=models.CharField(
                choices=[("normal", "通常動画"), ("live", "ライブ配信")],
                default="normal",
                max_length=10,
            ),
        ),
    ]
