# Generated by Django 5.1.2 on 2026-01-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0024_post_live_ended_post_video_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="live_ended",
            field=models.BooleanField(
                default=False, help_text="ライブ配信が終了している場合にチェック"
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="video_type",
            field=models.CharField(
                choices=[("normal", "通常動画"), ("live", "ライブ配信")],
                default="normal",
                max_length=10,
            ),
        ),
    ]
