# Generated by Django 5.1.2 on 2026-02-11 11:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0029_commentreport"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_hidden",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="is_hidden",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name="report",
            unique_together={("post", "reporter")},
        ),
    ]
