# Generated by Django 5.1.2 on 2026-02-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0030_comment_is_hidden_post_is_hidden_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="report_notice_level",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="post",
            name="report_notice_level",
            field=models.IntegerField(default=0),
        ),
    ]
