# Generated by Django 5.1.2 on 2026-03-14 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0032_comment_likes_alter_comment_video_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="likes",
        ),
        migrations.AlterField(
            model_name="comment",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="動画URL（YouTube / TikTok / Instagram / X / Facebook）",
                null=True,
            ),
        ),
    ]
