"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-08cid%x)8+1950pgoinlpfi-9ec%4x2fd)438)e81lok_&-n$!"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

import os

if os.getenv('DJANGO_ENV') == 'production':
    DEBUG = False
    ALLOWED_HOSTS = ['yourdomain.com', 'サーバーのIPアドレス']
else:
    DEBUG = True
    ALLOWED_HOSTS = ['127.0.0.1', 'localhost']

import os
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', '`mukumuku6')

SECURE_BROWSER_XSS_FILTER   = True
SECURE_CONTENT_TYPE_NOSNIFF = True

CSRF_COOKIE_SECURE    = True
SESSION_COOKIE_SECURE = True

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "diary.apps.DiaryConfig",
    "blog.apps.BlogConfig",
    "chat",
    "channels",
    "accounts",
    "user_messages",
    # "video_platform",
]

ASGI_APPLICATION = 'myproject.routing.application'
# ASGI_APPLICATION = "myproject.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "myproject.middleware.VisitorTrackingMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
]

ROOT_URLCONF = "myproject.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "accounts.context_processors.visitor_counts", 
            ],
        },
    },
]

WSGI_APPLICATION = "myproject.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # MySQLを使用
        'NAME': 'diary',                  # 作成したデータベース名
        'USER': 'takogaki',                    # 作成したユーザー名
        'PASSWORD': 'atjwbg28509224',          # パスワード
        'HOST': 'localhost',                   # データベースホスト（ローカルなら'localhost'）
        'PORT': '3306',
        'OPTIONS': {
            'charset': 'utf8mb4',              # 日本語対応のため
        },                                     # MySQLのデフォルトポート
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "ja"

TIME_ZONE = "Asia/Tokyo"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

MEDIA_ROOT = BASE_DIR / "media"

MEDIA_URL = "/media/"

SIGNUP_REDIRECT_URL = '/diary/'  # 新規登録後に遷移するURL

LOGIN_URL = '/accounts/login/'  # ログインページのURLを指定

LOGIN_REDIRECT_URL = "/diary/"

LOGOUT_REDIRECT_URL = "/accounts/login/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '192.168.11.37']

STATIC_URL = '/static/'
MEDIA_URL = '/media/'

# settings.py
AUTH_USER_MODEL = 'accounts.CustomUser'

# settings.py
DEFAULT_FROM_EMAIL = 'noreply@example.com'  # 共有の送信元アドレス

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # SMTPサーバー（例: Gmailなら'smtp.gmail.com'）
EMAIL_PORT = 587  # 一般的に587を使用
EMAIL_USE_TLS = True  # 安全な接続を使用
EMAIL_HOST_USER = 'takogaki.1114@gmail.com'  # 固定のメールアドレス
EMAIL_HOST_PASSWORD = 'yxxe kiix swuh uxte'  # そのメールアドレスのパスワード
DEFAULT_FROM_EMAIL = 'takogaki.1114@gmail.com'  # 固定の送信元アドレス

# メッセージのストレージバックエンドを設定
MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'

CSRF_TRUSTED_ORIGINS = ['http://127.0.0.1:8000']