# Generated by Django 5.1.2 on 2026-01-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videochat", "0004_alter_joinrequest_room_alter_joinrequest_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="videoroom",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="room_thumbnails/"
            ),
        ),
    ]
