# Generated by Django 5.1.2 on 2026-01-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videochat", "0005_videoroom_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="videoroom",
            name="ast_heartbeat",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
