# Generated by Django 5.1.2 on 2026-01-31 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videochat", "0006_videoroom_last_heartbeat"),
    ]

    operations = [
        migrations.AddField(
            model_name="videoroom",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
