# Generated by Django 5.1.2 on 2026-01-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videochat", "0006_videoroom_ast_heartbeat"),
    ]

    operations = [
        migrations.AddField(
            model_name="videoroom",
            name="last_heartbeat",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
