# Generated by Django 5.1.2 on 2026-02-01 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("videochat", "0007_videoroom_is_active"),
    ]

    operations = [
        migrations.RenameField(
            model_name="videoroom",
            old_name="last_heartbeat",
            new_name="last_joined_at",
        ),
        migrations.RemoveField(
            model_name="videoroom",
            name="is_active",
        ),
    ]
