# Generated by Django 6.0.4 on 2026-08-11 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Advertisement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="プログラム名")),
                (
                    "html",
                    models.TextField(
                        help_text="A8.netの「素材をコピー」で取得したHTMLをそのまま貼り付けてください。",
                        verbose_name="広告素材HTML",
                    ),
                ),
                (
                    "placement",
                    models.CharField(
                        choices=[("feed", "Feed"), ("frontpage", "Frontpage")],
                        default="feed",
                        max_length=50,
                        verbose_name="掲載場所",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
