# Generated by Django 6.0.4 on 2026-08-11 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advertisements", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="advertisement",
            name="html",
        ),
        migrations.AddField(
            model_name="advertisement",
            name="ad_url",
            field=models.URLField(
                blank=True,
                help_text="A8.netの広告リンクURLを入力してください。",
                max_length=1000,
                verbose_name="広告URL",
            ),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="A8.netの広告画像URLを入力してください。",
                max_length=2000,
                verbose_name="画像URL",
            ),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="tracking_url",
            field=models.URLField(
                blank=True,
                help_text="A8.netから提供された1px計測URLを入力してください。",
                max_length=2000,
                verbose_name="1px計測URL",
            ),
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="placement",
            field=models.CharField(
                choices=[
                    ("feed", "Feed"),
                    ("frontpage", "Frontpage"),
                    ("both", "両方"),
                ],
                default="feed",
                max_length=50,
                verbose_name="掲載場所",
            ),
        ),
    ]
