# Generated by Django 6.0.4 on 2026-08-11 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "advertisements",
            "0002_remove_advertisement_html_advertisement_ad_url_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="advertisement",
            name="ad_url",
        ),
        migrations.RemoveField(
            model_name="advertisement",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="advertisement",
            name="tracking_url",
        ),
        migrations.AddField(
            model_name="advertisement",
            name="html",
            field=models.TextField(
                blank=True,
                default="",
                help_text="A8.netの「素材をコピー」で取得したHTMLをそのまま貼り付けてください。",
                verbose_name="A8広告素材HTML",
            ),
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="placement",
            field=models.CharField(
                choices=[
                    ("feed", "Feed"),
                    ("frontpage", "Frontpage"),
                    ("both", "Feed ＋ Frontpage"),
                ],
                default="feed",
                max_length=50,
                verbose_name="掲載場所",
            ),
        ),
    ]
