# Generated by Django 6.0.4 on 2026-08-11 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advertisements", "0004_alter_advertisement_placement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="placement",
            field=models.CharField(
                choices=[
                    ("feed", "Feed"),
                    ("frontpage", "Frontpage"),
                    ("user_list", "User List"),
                    ("both", "全て"),
                ],
                default="feed",
                max_length=50,
                verbose_name="掲載場所",
            ),
        ),
    ]
