# Generated by Django 5.1.2 on 2026-01-27 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_messages", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["-sent_at"]},
        ),
    ]
