# Generated by Django 6.0.4 on 2026-05-06 00:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_messages", "0002_alter_message_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["sent_at"]},
        ),
        migrations.AddField(
            model_name="message",
            name="read_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["sender", "recipient"], name="user_messag_sender__18c651_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["recipient", "is_read"], name="user_messag_recipie_94b845_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["sent_at"], name="user_messag_sent_at_08b5d1_idx"
            ),
        ),
    ]
