# Generated by Django 5.1.2 on 2026-01-19 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = []
