# Generated by Django 5.1.2 on 2026-04-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_notification_post_alter_notification_actor_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="target_url",
        ),
        migrations.AddField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("like", "いいね"),
                    ("footprint", "足跡"),
                    ("match", "マッチ"),
                    ("comment", "コメント"),
                    ("system", "システム"),
                ],
                default="system",
                max_length=50,
            ),
        ),
    ]
