# Generated by Django 6.0.4 on 2026-08-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_remove_notification_target_url_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("like", "いいね"),
                    ("footprint", "足跡"),
                    ("match", "マッチ"),
                    ("comment", "コメント"),
                    ("message", "メッセージ"),
                    ("tag_match", "タグ一致"),
                    ("system", "システム"),
                ],
                default="system",
                max_length=50,
            ),
        ),
    ]
